### PR TITLE
Output Rewrite + Other Adjustments

### PR DESCRIPTION
**Pull request by robneu**
I've completely rewritten output.php and made a few changes to the other files. Everything seems to be functioning normally now.

### CODE REVIEW

**Comment by pmgllc** [comment]
Thanks. Brandon made some changes at 1:30 so I'll see what both of you changed and then I'll ask the collective how we submit a plugin w/ 4 authors.

I suppose I will also see if there are any copy changes I'd made for UX.

**Comment by kraftbj** [comment]
After church, I'll start a readme.txt for the WordPress.org repo. I know
how to list four authors there, not sure best ways to do multiples for the
plugin headers.

## 

Brandon Kraft
Coffea Web Services
http://coffeaweb.com // http://brandonkraft.com
@kraft

**Comment by robneu** [comment]
FYI I've got a working demo setup at http://itsnotlive.com/jesse/ I think I got everything working the way Jesse wanted it, but let me know if I missed anything.

I'm gonna go pass out for a while. I'll be around later.

**Comment by pmgllc** [comment]
I'll see if I have time before we leave. Very full day. You guys rock.

**Comment by pmgllc** [comment]
Great work! All of the functionality I envisioned is there. It's just got a few extra "features" we didn't intend and probably aren't showing up on your basic sandbox.

I've got a couple of items that are behaving differently - I think there are some conditional statements missing. You don't have to fix these to launch today because I would like to see if I can at least locate the problems even if I can't fix them.

The homepage banner is appearing twice, so I'll look later to see what is pulling that in twice.

Screen Shot 2013-01-06 at 7 59 46 AM

On a post where I am using both the banner image (which I think the UI should state that this is the banner image - I can _definitely_ fix that) and the featured image, they both appear and they appear oddly. See image below. The top one is the proper aspect ratio, but it's supposed to be 1600px wide. The bottom one is a smaller image but is being blown up full-size.

Existing posts with just a featured image as the banner size do still appear correctly, so this only appears when both images are being used.

Screen Shot 2013-01-06 at 8 01 54 AM

The blog index page now when set to display featured images CAN and DOES pull in the correct aspect ratio, so I'll just rebuild a proper homepage thumbnail for the homepage grid loop.

I don't see why we can't fix these things tonight. We've got a major life change happening today, so I'll be tied up all day until people go to bed.

**Comment by robneu** [comment]
I'm not sure what would be causing some of those... The way I set it up is for the featured image to function as the banner image since that's how the theme originally handled it. The "Custom" image is then handled as a smaller, secondary image that gets inserted into the post content. If there's no custom image present, a resized version of the featured image is inserted into the content instead. You probably need to regenerate your thumbnails for it to work correctly. Let me know if you need any help debugging or want to change anything. :)

**Pull request merged**
